version: "3.5"
services:
    # Serviço do django
    django-caco:
        container_name: django-caco
        # Pasta que contém o Dockerfile (instrução para configurar o container)
        build: ./django-site
        # Deverá sempre estar ativo
        restart: always
        environment:
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
        expose:
            # Mostraremos a porta 8080 entre containers (para o nginx)
            - "8080"
        # Aguardamos o banco de dados para iniciar o servidor django
        depends_on:
            - database
        volumes:
            # Montamos a pasta django-site/djangosite/ (projeto django) em
            # /djangosite no container
            - ./django-site/djangosite:/djangosite
            - /var/run/postgresql:/var/run/postgresql

    # Serviço do banco de dados
    database:
        container_name: database-postgresql
        image: postgres:10.4-alpine
        environment:
            - POSTGRES_DB=postgresql
            - POSTGRES_USER=postgresql
            - POSTGRES_PASSWORD=postgresql
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
        volumes:
            # Passamos o banco de dados para a nossa pasta
            - ./database_data:/var/lib/postgresql/data
            # Passamos a ligação por um UNIX socket
            - /var/run/postgresql:/var/run/postgresql
        restart: always

    # Serviço do nginx
    servidor:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile-http
        restart: always
        environment:
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
        ports:
            - target: 80
              published: 80
              mode: host
              protocol: tcp
        volumes:
            # Montamos as pastas django-site/djnangosite/media e
            # django-site/djangosite/djangosite/adminstatic em /media e /static
            # respectivamente do container para ser servido pelo nginx (mais
            # rápido)
            - ./django-site/djangosite/media:/media
            - ./django-site/djangosite/static:/static
        depends_on:
            - django-caco
        links:
            # nginx se conectará ao django
            - "django-caco:django-caco"
